### ISSUE TITLE
列表形式，页面退出后计时器未销毁，会内存泄漏 

### ISSUE THREAD

**Issue by hOlMoo** [xiaozhizhong/animate_countdown_text#1]
列表形式，页面退出后计时器未销毁，会内存泄漏

**Comment by xiaozhizhong** [comment]
有复现的demo吗？我自己也有项目在用这个插件，并且也是列表，但是没有发现这个情况。

**Comment by hOlMoo** [comment]
https://github.com/hOlMoo/flutter_test_countdown_text.  我写了个测试demo，你可以看看打印日志

**Comment by xiaozhizhong** [comment]
试了一下你的demo，销毁页面后log仍然一直输出，问题应该出现在BroadcastStream未被取消上。1.1.3版本已发布，修复了这个问题，感谢反馈。

**Comment by hOlMoo** [comment]
ok~ 感谢修改
